/* 
문자열 합치는 함수
CONCAT(expression1, expression2, expression3, ...)
*/
SELECT CONCAT(OCCUPATIONS.NAME, '(', SUBSTR(OCCUPATIONS.OCCUPATION, 1, 1), ')') AS N
FROM OCCUPATIONS
ORDER BY N;
SELECT CONCAT('There are a total of ', COUNT(OCCUPATIONS.OCCUPATION), ' ', LOWER(OCCUPATIONS.OCCUPATION), 's.')
FROM OCCUPATIONS
GROUP BY OCCUPATIONS.OCCUPATION
ORDER BY COUNT(OCCUPATIONS.OCCUPATION), OCCUPATIONS.OCCUPATION;